### ISSUE TITLE
Protocol string prepend

### ISSUE THREAD

**Issue by cesarpose** [michenriksen/aquatone#123]
Hi! Thanks for a great tool.

When I run command "cat hosts.txt | aquatone" I have not results. I had to prepend the protocol string to every entry in the file input for aquatone to take it. I reviewed the url.go in core and seems to be all good. Maybe I don't understand so much of go code. For solve this I prepend protocol string with awk for now.
I have go 1.11.1 version on linux.

**Comment by michenriksen** [comment]
Looking at the [screenshot you posted on Twitter](https://twitter.com/bughuntercat/status/1059099415049367554), Aquatone is correctly picking up the hosts from the input. When Aquatone finds hostnames/domains, they undergo port scanning in order to turn them into URLs like `http://admin.example.com/` and `https://admin.example.com:8443/`. 

I think the issue you're experiencing is that the port scan probes that are timing out, so Aquatone won't find any URLs to screenshot. If you are on a slow connection, you might want to increase the scan timeout with the `-scan-timeout` flag, to something like 100 milliseconds or more:

    $ cat hosts.txt | aquatone -scan-timeout 100

This would also explain why it worked for you when adding `http://` in front of the hosts, because Aquatone will assume that URLs are alive and won't be port scanned, and the timeout for requesting and screenshotting URLs is much higher.

**Comment by cesarpose** [comment]
Doesn't work, only works if I add the protocol string prefix. I idon't know why. Aquatone seems to read right the input file but thare are not screenshots if I don't add that.

**Comment by cesarpose** [comment]
Well, I set -scan-timeout to 150 or more and works fine.
