### ISSUE TITLE
Too many timeout with aquatone-gather

### ISSUE THREAD

**Issue by phackt** [michenriksen/aquatone#50]
Hello Michael,
First thanks for sharing this great tool. However with aquatone-gather i often have some timeout issues while i succeed in manually accessing them. I'm pretty sure it comes with the nightmare.js lib. Is somebody facing this kind of issue or is there a way to increase the timeout?

Example:
![aquatone](https://user-images.githubusercontent.com/19553457/30852364-d351225e-a2ab-11e7-9468-fe109458d5dd.jpg)

Thanks,
Phackt

**Comment by michenriksen** [comment]
Hi there, aquatone-gather can be a bit flaky because of many different things, such as internet connection speed, threads being used, target endpoint responsiveness and so on. If you type `aquatone-gather --help` you can see different options to use. Try playing around with `--timeout` and `--threads` and see if it helps.

**Comment by phackt** [comment]
Ok thanks i'm currently doing this kind of test i will let you know, thanks.
